version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: vehicles_user
      MYSQL_PASSWORD: vehicles_password
      MYSQL_DATABASE: vehicles_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    environment:
      VEHICLES_DB_USERNAME: vehicles_user
      VEHICLES_DB_PASSWORD: vehicles_password
      VEHICLES_DB_NAME: vehicles_db
      VEHICLES_DB_HOST: db
    depends_on:
      - db
    volumes:
      - .:/app=

volumes:
  db_data:
